### ISSUE TITLE
Custom Controllers wiki update

### ISSUE THREAD

**Issue by shawsers** [turbonomic/kubeturbo#885]
Please update the documentation for the point below at the link: [https://github.com/turbonomic/kubeturbo/wiki/Action-Details#pod-move-actions-technical-details](https://github.com/turbonomic/kubeturbo/wiki/Action-Details#pod-move-actions-technical-details)

- Custom Controllers (such as CatalogSource and Benchmark) may fail execution if Kubeturbo cannot spin up a copy, and may require support of the controller. If this is the case, open an IBM Idea here: [https://ideas.ibm.com](https://ideas.ibm.com) for a future enhancement for support.

**Comment by evat-pm** [comment]
Impossible to keep up with Custom Controllers and providing examples is not helpful given the action failure is explicit.  Did implement the good suggestion to open an IBM Idea rather than suggesting the user open a bug.  Content updated here https://github.com/turbonomic/kubeturbo/wiki/Action-Details#pod-move-actions-technical-details and issue is closed.
